uwblueprint/feeding-canadian-kids

backend/app/__init__.py, backend/app/graphql/__init__.py, backend/app/graphql/error_handling.py, backend/app/middlewares/auth.py, backend/app/middlewares/validate.py, backend/app/models/__init__.py, backend/app/resources/entity_dto.py, backend/app/rest/auth_routes.py, backend/app/rest/entity_routes.py, backend/app/rest/simple_entity_routes.py, backend/app/rest/user_routes.py, backend/app/services/implementations/auth_service.py, backend/app/services/implementations/email_service.py, backend/app/services/implementations/user_service.py, backend/app/services/interfaces/auth_service.py, backend/app/services/interfaces/file_storage_service.py, backend/app/services/interfaces/user_service.py, backend/app/utilities/csv_utils.py, backend/app/utilities/firebase_rest_client.py, backend/requirements.txt, backend/setup.cfg, backend/tests/functional/test_user_routes.py, backend/tests/unit/test_csv.py
None
- Add linter configuration
- Fixup code to match linter complaints
1. `docker-compose up --build`
2. `docker exec -it fck_backend /bin/bash -c 'black . && flake8 .'`
* Are the linter rules/config good?
=> Setup linter

.github/workflows/test.yml, backend/tests/functional/conftest.py, backend/tests/functional/test_user_routes.py, backend/tests/functional/test_user_service.py
[Ticket Name](https://app.zenhub.com/workspaces/fck-627480c10d8974001872b0ef/board)
*
1.
*
=> Fix test workflow

frontend/src/Routes.tsx, frontend/src/components/auth/Join.tsx, frontend/src/components/auth/Login.tsx, frontend/src/components/auth/ResetPassword.tsx, frontend/src/components/pages/Dashboard.tsx, frontend/src/constants/Routes.ts, frontend/src/theme/foundations/colors.js
[Onboarding: Reset Password UI](https://app.zenhub.com/workspaces/fck-627480c10d8974001872b0ef/issues/gh/uwblueprint/feeding-canadian-kids/41)
* Adds a front-end route and UI at /reset-password
* Error validation for new password being too short or not matching
* Responsive to mobile
1. Enter a password, and another different password that doesn't match for "Confirm your password"
2. Click the 'Reset' button and verify that a relevant error message appears
3. Enter matching passwords that are less than 8 characters long
4. Click the 'Reset' button and verify that a relevant error message appears
5. Enter matching passwords that are 8 characters or longer
6. Click the 'Reset' button and verify that all error messages go away
* Checking that it's responsive! Also checking that it matches …
=> 41 Reset password UI

frontend/src/Routes.tsx, frontend/src/components/auth/ForgotPassword.tsx, frontend/src/constants/Routes.ts, frontend/src/theme/components/formlabel.ts, frontend/src/theme/components/text.ts
[Onboarding: Forgot Password UI](https://app.zenhub.com/workspaces/fck-627480c10d8974001872b0ef/issues/gh/uwblueprint/feeding-canadian-kids/40)
* Created the frontend for forgot password
1. Check with Figma
2. Check responsiveness
* Checking for responsiveness
=> Onboarding: Forgot Password UI

frontend/src/components/auth/ForgotPassword.tsx
#56 
* Added necessary graphQL calls in frontend to call forget pwd
1. Test with a user that exists both in the same environment in firebase and mongo as well
*
=> Forgot PWD functionality 

.github/PULL_REQUEST_TEMPLATE.md, README.md
[Update the Pull Request Readme and Main Readme.md](https://www.notion.so/uwblueprintexecs/Update-the-Pull-Request-Readme-and-Main-Readme-md-9e826ef54d2742fcb8700da9363a5962?pvs=4)
* Added the necessary changes to the ReadMe files as instructed on the ticker.
1. Changes in the PR match the changes instructed on the ticket
* Ensuring grammatical mistakes are not made on an changes included
=> Update the Pull Request Readme and Main Readme.md

backend/app/graphql/__init__.py, backend/app/graphql/meal_request.py, backend/app/graphql/types.py, backend/app/models/meal_request.py, backend/app/resources/meal_request_dto.py, backend/app/resources/validate_utils.py, backend/app/services/implementations/meal_request_service.py, backend/app/services/interfaces/meal_request_service.py, backend/requirements.txt, backend/tests/graphql/test_meal_request.py, frontend/yarn.lock
[Create Query for getting all food requests for one user](https://www.notion.so/uwblueprintexecs/Create-Query-for-getting-all-food-requests-for-one-user-e1effb42d80540bb8923ed9315e0bdf1?pvs=4)
* The query is used to retrieve all meal requests made by an ASP, using their user ID when executing the query
* Several query parameters can be used when executing the query: requestor ID (required), minimum drop off date, maximum drop off date, status ("Open", "Fulfilled", "Cancelled"), offset, limit, and sort by date direction ("ASC", "DESC"). These query parameters will be used when in the calendar view, for filtering and pagination.
1. From the root directory, run `make betest` and ensure that all automated tests pass (no regressions)
2. In the GraphQL playground, execute a mutation to add a …
=> GraphQL query to retrieve all meal requests by requestor ID

backend/app/resources/validate_utils.py, backend/tests/graphql/conftest.py, backend/tests/graphql/mock_test_data.py, backend/tests/graphql/test_meal_request.py
N/A
* Created a `meal_request_setup` fixture that creates a mock requestor, donor, and meal request before running the test suites.
* Updated the `test_update_meal_request` test to use the mocked meal request rather than having to create a new one using the mutation.
* Created a `test_get_meal_request_by_requestor_id` to test the `getMealRequestsByRequestorId` query.
1. Run `make betest` from the root directory.
N/A
=> Improvements to meal request tests

backend/app/graphql/types.py, backend/app/graphql/user_queries.py, backend/app/resources/asp_distance_dto.py, backend/app/services/implementations/user_service.py, backend/app/services/interfaces/user_service.py, backend/app/utilities/location_to_coordinates.py, backend/tests/graphql/mock_test_data.py, backend/tests/graphql/test_all_user_queries.py
https://www.notion.so/uwblueprintexecs/Dev-e3112e78136f49b4b042e9a0d9df9723?p=404d7d68a38940f4957272ecb7523075&pm=s
* Returns all users with the role of ASP within a given max distance of the requesting user
* Results are sorted in increasing order of distance, with an option to pass in offset and limit
* Along with each user, returns distance away from the requesting user (in KM)
1. Backend tests are currently not possible due to lack of support from mongomock, query should be tested in GraphQL playground
2. To verify that distance is accurate (to a certain degree), you can use this website: https://www.mapdevelopers.com/distance_from_to.php
*
=> Create getASPNearLocation query

frontend/src/components/auth/Logout.tsx, frontend/src/components/common/Header.tsx, frontend/src/components/common/HeaderButtons.tsx, frontend/src/pages/Settings.tsx
[Replace with Ticket URL](https://www.notion.so/uwblueprintexecs/Dynamic-Headers-250a79bcad45405b9396b28ca16c0481?pvs=4)
* Added Dynamic Headers for different users
* Moved the logout button to the Settings page
* Changed the style of the Header to match Figma UI
1. Login as an ASP user and ensure that the following two buttons are in the header: 
- "Home"
- "Settings"
2. Login as a Meal Donor and ensure that the following three buttons are in the header: 
- "Schools"
- "My Donations"
- "Settings"
3. Login as an Admin user and ensure that the following four buttons are in the header: 
- "Meal Requests"
- "Onboarding Requests"
- "List of Users"
- "Settings" 
Note: Buttons 1-3 currently all navigate to the same page. Thus, if one of the three buttons are clicked on, they all appear "active" …
=> Dynamic Headers

frontend/src/components/donor/NearbySchoolList.tsx, frontend/src/pages/YourMatchesPage.tsx
=> Matches pagination

backend/app/graphql/__init__.py
=> Fix backend import

.github/actions/heroku-deploy/action.yml, .github/workflows/staging-heroku-deploy.yml
=> Add database name field to heroku deploy

backend/app/services/implementations/meal_request_service.py
=> Fix formatting

backend/app/config.py, backend/app/models/__init__.py
=> Use MG_DATABASE instead of MG_DB for consistency

.github/actions/heroku-deploy/action.yml, .github/workflows/staging-heroku-deploy.yml, backend/app/config.py, backend/app/models/__init__.py
=> Use DB_NAME instead of DATABASE_NAME

backend/app/services/implementations/meal_request_service.py, backend/app/services/implementations/reminder_email_service.py, backend/tests/graphql/test_reminder_email_service.py, frontend/.eslintrc.js, frontend/src/components/asp/requests/SchedulingFormCalendar.tsx, frontend/src/components/asp/requests/SchedulingFormReviewAndSubmit.tsx, frontend/src/components/common/MealRequestCalendarView.tsx, frontend/src/components/meal_donor/donation_form/MealDeliveryDetails.tsx, frontend/src/components/meal_donor/donation_form/MealDonationFormContactInfo.tsx, frontend/src/components/mealrequest/ASPListView.tsx, frontend/src/pages/ASPCalendar.tsx, frontend/src/pages/UpcomingPage.tsx, frontend/src/utils/convertTimeToUTC.ts, frontend/src/utils/useGetOnsiteContacts.ts
=> Fixed tricky timezone and date related bugs

backend/app/graphql/user_queries.py, backend/app/services/implementations/user_service.py, backend/app/services/interfaces/user_service.py
=> Fix getAllUsers

backend/app/graphql/meal_request.py, backend/app/models/meal_request.py, backend/app/resources/meal_request_dto.py, backend/app/services/implementations/meal_request_service.py, backend/app/services/implementations/reminder_email_service.py, backend/app/services/interfaces/meal_request_service.py, backend/tests/graphql/mock_test_data.py, backend/tests/graphql/test_meal_request.py, backend/tests/graphql/test_reminder_email_service.py, frontend/src/Routes.tsx, frontend/src/components/asp/requests/SchedulingFormReviewAndSubmit.tsx, frontend/src/components/common/MealRequestCalendarView.tsx, frontend/src/components/meal_donor/donation_form/MealDeliveryDetails.tsx, frontend/src/components/meal_donor/donation_form/MealDonationForm.tsx, frontend/src/components/meal_donor/donation_form/MealDonationFormReviewAndSubmit.tsx, frontend/src/components/mealrequest/ASPListView.tsx, frontend/src/pages/ASPCalendar.tsx, frontend/src/pages/EditMealRequestForm.tsx, frontend/src/pages/MealDonorCalendar.tsx, frontend/src/pages/UpcomingPage.tsx, frontend/src/types/MealRequestTypes.ts
Before each meal request stored an address. Now all meal requests use the user locations meal request instead.
=> Remove address from individual requests and instead use ASP address

backend/app/services/interfaces/user_service.py
=> Fix import error

backend/app/__init__.py
=> Show all missing environment variables in error message

backend/app/__init__.py
=> Detailed error message

frontend/src/components/auth/Join.tsx, frontend/src/components/auth/JoinSuccess.tsx, frontend/src/components/common/OnsiteContactSection.tsx
- Include city in prompt for address on sign up (just add a text that says)
- Don’t force people to have at least one onsite staff when signing up
- After you signup, the signup confirmation text shouldn’t say ASP on it
- Explain what onsite staff is on the sign up page
*
1.
*
=> Signup page improvements

frontend/src/components/donor/NearbySchoolList.tsx, frontend/src/pages/ASPCalendar.tsx
* Just changed a couple messages, let me know if you think these are better
=> Change messages

.github/workflows/prod-firebase-deploy.yml, .github/workflows/prod-heroku-deploy.yml
=> Setup basic prod deploy pipeline

frontend/src/components/asp/requests/SchedulingFormCalendar.tsx, frontend/src/components/asp/requests/SchedulingFormWeekly.tsx, frontend/src/components/meal_donor/donation_form/MealDeliveryDetails.tsx, frontend/src/components/mealrequest/ASPListView.tsx, frontend/src/components/mealrequest/MealDonorListView.tsx, frontend/src/pages/UpcomingPage.tsx
Displays dates as a range in:
1. ASP dashboard
2. When creating a meal request
3. Meal donation commitment
4. Meal donor upcoming donation list
5. Meal donor completed donation list
@shahanneda see my slack messages for screenshots of these
1. Check that all locations that have been changed appear as desired.
=> Display dates as a range
